ViewModels/CarsListViewModels.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class CarsListViewModels
    {
        public IEnumerable<Car> allCars { get; set; }

        public string currCategory { get; set; }
    }
}

ViewModels/HomeViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Car> favCars { get; set; }
    }
}

ViewModels/ShopCartViewModel.cs
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart{ get; set; }
    }
}

Controllers/CarsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class CarsController : Controller
    {
        private readonly IAllCars _allCars;
        private readonly ICarsCategory _allCatagories;

        public CarsController(IAllCars iAllCars, ICarsCategory iCarsCat)
        {
            _allCars = iAllCars;
            _allCatagories = iCarsCat;
        }

        [Route("Cars/List")]
        [Route("Cars/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Car> cars = null;
            string currCategory = "";

            if (string.IsNullOrEmpty(category))
            {
                cars = _allCars.Cars.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("electro", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("ElectroCars")).OrderBy(i => i.id);
                }
                else if (string.Equals("fuel", category, StringComparison.OrdinalIgnoreCase))
                {
                    cars = _allCars.Cars.Where(i => i.Category.categoryName.Equals("Classik Cars")).OrderBy(i => i.id);
                }

                currCategory = _category;
            }
            
            var carObj = new CarsListViewModels
            {
                allCars = cars,
                currCategory = currCategory
            };

            /*ViewBag.Category = "Some New";
            var cars = _allCars.Cars;
            return View(cars);*/


            /*CarsListViewModels obj = new CarsListViewModels();
            obj.allCars = _allCars.Cars;
            obj.currCategory = "CARS";*/

            ViewBag.Title = "CarShop";

            return View(carObj);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllCars _carRep;
        
        public HomeController(IAllCars carRep)
        {
            _carRep = carRep;
        }

        public ViewResult Index()
        {
            var homeCars = new HomeViewModel
            {
                favCars = _carRep.getFavCars
            };

            return View(homeCars);
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.listSHopItems = shopCart.getShopItems();

            if (shopCart.listSHopItems.Count == 0)
            {
                ModelState.AddModelError("", "You dont have any items");
            }

            if (ModelState.IsValid)
            {
                allOrders.createOrdre(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Ordred successfully was made";
            return View();
        }
    }
}

Controllers/ShopCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Shop.Data.Interfaces;
using Shop.Data.Models;
using Shop.Data.Repository;
using Shop.ViewModels;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private readonly IAllCars _carRep;
        private readonly ShopCart _shopCart;

        public ShopCartController(IAllCars carRep, ShopCart shopCart)
        {
            _carRep = carRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listSHopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _carRep.Cars.FirstOrDefault(i => i.id == id);

            if (item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("index");  //вказуємо яку ф-ї обробляємо
        }
    }
}

Views/Cars/List.cshtml
@*@model IEnumerable<Shop.Data.Models.Car>*@

@*@using Shop.ViewModels
@model CarsListViewModels*@

@*@{
    Layout = "_Layout";
}*@


    <h2>All cars</h2>
    @*<h1>@ViewBag.Category</h1>*@
    <h1>@Model.currCategory</h1>
    @*@foreach (var car in Model )
        {
            <div>
                <h2>Model: @car.name</h2>
                <p>Price: @car.price.ToString("c")</p>
            </div>
        }*@


<div class="row mt-5 mb-2">
    @foreach (Car car in Model.allCars)
    {
        @Html.Partial("AllCars", car)
    }
</div>

Views/Home/Index.cshtml
@model HomeViewModel

<h2>Best cars</h2>

<div class="row mt-5 mb-2">
    @foreach (Car car in Model.favCars)
    {
        @Html.Partial("AllCars", car)
    }
</div>

Views/Order/Checkout.cshtml
@model Order

<div class="row">
    <h3>Making order</h3>

    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="form-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="surname"></label>
            <div class="col-md-5">
                <input asp-for="surname" class="form-control" />
                <span asp-validation-for="surname" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="address"></label>
            <div class="col-md-5">
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>

        <input class="btn btn-success" type ="submit" value="Order" />
    </form>
</div>

Views/Order/Complete.cshtml
<h3>@ViewBag.Message</h3>

Views/Shared/AllCars.cshtml
@model Car

    <div class="col-lg-4">
        <img class="img-thumbnail" src="@Model.img" alt="@Model.name" />
        <h2> @Model.name</h2>
        <p>@Model.price.ToString("c")</p>
        <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Add to cart</a></p>
    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="/css/StyleSheet.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <a class="navbar-brand" href="#">ITProgerKOS</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Main <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/cars/list">All cars</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="/cars/list/electro" tabindex="-1">Electro</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="/cars/list/fuel" tabindex="-1">Fuel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="/ShopCart" tabindex="-1">Cart</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>

    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>© 2020 Company, Inc. · <a href="#">Privacy</a> </p>
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div class="container">
    @foreach (var el in Model.shopCart.listSHopItems)
    {
        <div class="alert-warning mt-3">
            <b>Car:</b>@el.car.name<br/>
            <b>Price:</b>@el.car.price.ToString("c")
        </div>
    }
    <hr/>
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Buy</a>
</div>